version: '3.7'

services:

  fluentd:
    build: .
    container_name: fluentd
    ports:
      - '5140:5140/udp'
      - '24224:24224'
      - '24231:24231'
    extra_hosts:
      - 'esc:10.0.0.31'
    restart: always
