{
 "title": "cpu_core",
 "description": "%cpu utilization by mode (up to 8 cores)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu_seconds_total{job=\"node\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU-0",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"0\",mode=\"user\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"0\",mode=\"system\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"0\",mode=\"iowait\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"0\",mode=\"softirq\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU-1",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"1\",mode=\"user\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"1\",mode=\"system\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"1\",mode=\"iowait\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"1\",mode=\"softirq\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU-2",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"2\",mode=\"user\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"2\",mode=\"system\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"2\",mode=\"iowait\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"2\",mode=\"softirq\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU-3",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"3\",mode=\"user\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"3\",mode=\"system\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"3\",mode=\"iowait\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"3\",mode=\"softirq\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU-4",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"4\",mode=\"user\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"4\",mode=\"system\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"4\",mode=\"iowait\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"4\",mode=\"softirq\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU-5",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"5\",mode=\"user\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"5\",mode=\"system\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"5\",mode=\"iowait\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"5\",mode=\"softirq\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU-6",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"6\",mode=\"user\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"6\",mode=\"system\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"6\",mode=\"iowait\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"6\",mode=\"softirq\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU-7",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"7\",mode=\"user\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"7\",mode=\"system\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"7\",mode=\"iowait\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node\",cpu=\"7\",mode=\"softirq\",instance=~\"$node\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}