{
 "title": "grafana",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"grafana\"})",
     "legendFormat": "resident"
    },
    {
     "expr": "sum(process_virtual_memory_bytes{job=\"grafana\"})",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (statuscode) (irate(http_request_total{job='grafana'}[5m]))",
     "legendFormat": "{{statuscode}}"
    }
   ]
  },
  {
   "title": "Request Duration - 0.99",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_milliseconds{job=\"grafana\", quantile=\"0.99\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}