{
 "title": "network",
 "description": "bytes/packets transmit/receive",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu_seconds_total{job=\"node\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes - transmit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Bytes - receive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Packets - transmit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"node\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Packets - receive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"node\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}