version: '3.7'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.10.0
    volumes:
      - ./data_prometheus:/prometheus/data
      - ./prometheus.yml:/prometheus/prometheus.yml
    networks:
      - monitor
    # ports:
    #   - "9090:9090"
    restart: always
    command:
      - '--storage.tsdb.retention.time=365d'
    # extra_hosts:
    #   - "esc:172.23.0.1"

  grafana:
    container_name: grafana
    depends_on:
      - prometheus
    image: grafana/grafana:6.2.1
    volumes:
      - ./data_grafana:/var/lib/grafana
    networks:
      - monitor
    ports:
      - "3000:3000"
    restart: always

networks:
  monitor: {}
