version: '3.7'

services:

  prometheus:
    image: prom/prometheus:v2.12.0
    container_name: prometheus
    volumes:
      - ./data_prometheus:/prometheus/data
      - ./prometheus.yml:/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    command:
      - '--storage.tsdb.retention.time=365d'
      - '--log.format=json'
    extra_hosts:
      - 'esc:10.0.0.31'
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: json
    restart: always

  grafana:
    image: grafana/grafana:6.3.5
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - ./data_grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: kv
    restart: always