---

global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'm0n1t0r'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'node'
    static_configs:
      - targets:
        - esc:9100
