version: '3.3'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.10.0
    volumes:
      - ./prometheus/data:/prometheus/data
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
    networks:
      - monitor
    # ports:
    #   - "9090:9090"
    restart: always
    command:
      - '--storage.tsdb.retention.time=365d'
    extra_hosts:
      - "esc:10.92.124.1"

  grafana:
    container_name: grafana
    depends_on:
      - prometheus
    image: grafana/grafana:6.2.1
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - monitor
    ports:
      - "3000:3000"
    restart: always

networks:
  monitor: {}
