version: '3.7'

services:
  db:
    image: mariadb:10.4.7-bionic
    container_name: mariadb
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: asdfasdf
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: asdfasdf
    restart: always