version: '3.7'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.2.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      nproc: 4096
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./data/:/usr/share/elasticsearch/data
    networks:
      - elasticstack
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

  kibana:
    container_name: kibana
    depends_on:
      - elasticsearch
    image: kibana:7.2.0
    environment:
      - "XPACK_MONITORING_ENABLED=false"
    networks:
      - elasticstack
    ports:
      - "5601:5601"
    restart: always

networks:
  elasticstack: {}